version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    networks:
      - app-network

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./database:/var/lib/postgresql/data/
      - ./pms_db_backup.sql:/home/pms_db_backup.sql
    environment:
      - POSTGRES_USER=pms
      - POSTGRES_PASSWORD=pms
      - POSTGRES_DB=pms
    ports:
      - 5433:5432
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge