# Generated by Django 3.0.7 on 2021-10-05 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expenses_monthlypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_date',
            field=models.DateField(default=datetime.date(2021, 10, 5)),
        ),
    ]
