# Generated by Django 3.0.7 on 2021-10-06 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211005_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_date',
            field=models.DateField(default=datetime.date(2021, 10, 6)),
        ),
    ]
