# Generated by Django 3.0.7 on 2021-10-06 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20211006_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
