# Generated by Django 3.0.7 on 2021-10-13 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20211013_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
