# Generated by Django 3.0.7 on 2021-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20211013_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.CharField(choices=[(1, 'Fixed'), (2, 'Changeable')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
