# Generated by Django 3.0.7 on 2021-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expenses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.IntegerField(choices=[('1', 'Fixed'), ('2', 'Changeable')]),
        ),
    ]
