# Generated by Django 3.0.7 on 2021-10-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20211013_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='type',
            new_name='pay_type',
        ),
    ]
