# Generated by Django 3.0.7 on 2021-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20211013_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.CharField(choices=[('rental', 'Rental'), ('emi', 'EMI'), ('bill', 'Bill'), ('chit', 'Chit'), ('repayment', 'RE-Payment'), ('credit_card', 'Credit Card'), ('others', 'Others')], default='others', max_length=50),
            preserve_default=False,
        ),
    ]
