# Generated by Django 3.0.7 on 2021-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20211013_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.CharField(choices=[('rental', 'Rental'), ('emi', 'EMI'), ('bill', 'Bill'), ('chit', 'Chit'), ('savings', 'Savings'), ('repayment', 'RE-Payment'), ('credit_card', 'Credit Card'), ('others', 'Others')], max_length=50),
        ),
    ]
