# Generated by Django 3.0.7 on 2021-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20211013_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'salary'), ('finance', 'Finance'), ('car_rental', 'Car Rental'), ('others', 'Others')], max_length=50),
        ),
    ]
