# Generated by Django 3.0.7 on 2021-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20211013_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
