# Generated by Django 3.0.7 on 2021-10-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_expenses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Income'),
        ),
    ]
