# Generated by Django 3.0.7 on 2021-10-13 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_monthlypayment_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
