# Generated by Django 3.0.7 on 2021-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20211013_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
