# Generated by Django 3.0.7 on 2021-10-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20211013_2105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlypayment',
            unique_together={('month', 'income', 'expense')},
        ),
    ]
