# Generated by Django 3.0.7 on 2021-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20211014_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='sort_order',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='income',
            name='sort_order',
            field=models.IntegerField(default=999),
        ),
    ]
