# Generated by Django 3.0.7 on 2021-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20211016_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='savings',
            field=models.BooleanField(default=False),
        ),
    ]
