# Generated by Django 3.0.7 on 2021-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20211017_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'salary'), ('finance', 'Finance'), ('car_rental', 'Car Rental'), ('emi', 'EMI'), ('rent', 'Rent'), ('others', 'Others')], max_length=50),
        ),
    ]
