# Generated by Django 3.0.7 on 2021-10-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20211017_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dim_income_source',
            },
        ),
    ]
