# Generated by Django 3.0.7 on 2021-10-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_incomesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.IncomeSource'),
            preserve_default=False,
        ),
    ]
