# Generated by Django 3.0.7 on 2021-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('finance', 'Finance'), ('car_rental', 'Car Rental'), ('emi', 'EMI'), ('rent', 'Rent'), ('others', 'Others')], max_length=50),
        ),
    ]
