# Generated by Django 3.0.7 on 2021-10-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20211021_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dim_finance_source',
            },
        ),
        migrations.RunSQL("INSERT INTO dim_finance_source SELECT * FROM dim_income_source;"),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='finance.FinanceSource'),
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
    ]
