# Generated by Django 3.0.7 on 2021-10-23 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20211022_1940'),
    ]

    operations = [

        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_date', models.DateField(null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceSource')),
            ],
            options={
                'db_table': 'fact_credit',
            },
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Credit'),
        ),
    ]
