# Generated by Django 3.0.7 on 2021-10-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20211023_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
