# Generated by Django 3.0.7 on 2021-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_auto_20211023_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('finance', 'Finance'), ('car_rental', 'Car Rental'), ('emi', 'EMI'), ('rent', 'Rent'), ('credit', 'Credit Return'), ('others', 'Others')], max_length=50),
        ),
    ]
