# Generated by Django 3.0.7 on 2021-10-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_auto_20211023_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='credit',
            name='type',
            field=models.IntegerField(choices=[(1, 'Credit')], default=1),
        ),
    ]
