# Generated by Django 3.0.7 on 2021-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_remove_credit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
