# Generated by Django 3.0.7 on 2021-10-26 11:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_credit_expected_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='credit',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
