# Generated by Django 3.0.7 on 2021-10-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0020_auto_20211026_1728'),
        ('finance', '0039_auto_20211026_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='chit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Chit'),
        ),
    ]
