# Generated by Django 3.0.7 on 2021-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0041_flexiloan_flexiutilized'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexiutilized',
            name='payment_type',
            field=models.CharField(choices=[('repayment', 'Re-Payment'), ('withdraw', 'Withdraw')], default='repayment', max_length=50),
            preserve_default=False,
        ),
    ]
