# Generated by Django 3.0.7 on 2021-10-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0042_flexiutilized_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexiloan',
            name='utilized_amount',
            field=models.DecimalField(decimal_places=2, default=1452999, max_digits=15),
            preserve_default=False,
        ),
    ]
