# Generated by Django 3.0.7 on 2021-10-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_flexiloan_utilized_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlexiLoan',
            new_name='FinanceLoan',
        ),
        migrations.RenameModel(
            old_name='FlexiUtilized',
            new_name='FinanceUtilized',
        ),
        migrations.RenameField(
            model_name='financeutilized',
            old_name='flexi',
            new_name='finance',
        ),
        migrations.AlterModelTable(
            name='financeloan',
            table='dim_finance_loan',
        ),
        migrations.AlterModelTable(
            name='financeutilized',
            table='fact_finance_utilized',
        ),
    ]
