# Generated by Django 3.0.7 on 2021-10-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_auto_20211027_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='finance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceLoan'),
        ),
    ]
