# Generated by Django 3.0.7 on 2021-10-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0020_auto_20211026_1728'),
        ('finance', '0045_expenses_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='chit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Chit'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceLoan'),
        ),
    ]
