# Generated by Django 3.0.7 on 2021-10-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_auto_20211027_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceLoan'),
        ),
    ]
