# Generated by Django 3.0.7 on 2021-09-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('settlement_date', models.IntegerField(default=5)),
                ('total_value', models.IntegerField()),
                ('total_months', models.IntegerField()),
            ],
            options={
                'db_table': 'dim_chit',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'dim_customers',
            },
        ),
        migrations.CreateModel(
            name='ChitCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('prefered_month', models.DateField()),
                ('chit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Customers')),
            ],
            options={
                'db_table': 'fact_chit_customers',
            },
        ),
    ]
