# Generated by Django 3.0.7 on 2021-09-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0002_auto_20210907_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
