# Generated by Django 3.0.7 on 2021-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0003_auto_20210907_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitcustomers',
            name='prefered_month',
            field=models.DateField(null=True),
        ),
    ]
