# Generated by Django 3.0.7 on 2021-09-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0004_auto_20210907_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitcustomers',
            name='prefered_month',
        ),
    ]
