# Generated by Django 3.0.7 on 2021-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0006_chitcustomers_prefered_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitcustomers',
            name='prefered_month',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
