# Generated by Django 3.0.7 on 2021-09-14 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0007_auto_20210907_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('paid_date', models.DateField()),
                ('chit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Customers')),
            ],
            options={
                'db_table': 'fact_chit_payment',
            },
        ),
    ]
