# Generated by Django 3.0.7 on 2021-09-23 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0008_chitpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitpayment',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
