# Generated by Django 3.0.7 on 2021-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0010_chit_interest_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chit',
            name='commision_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=15),
        ),
    ]
