# Generated by Django 3.0.7 on 2021-10-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0011_chit_commision_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField()),
                ('chit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit.Customers')),
            ],
            options={
                'db_table': 'fact_chit_settlement',
            },
        ),
    ]
