# Generated by Django 3.0.7 on 2021-10-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0012_chitsettlement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chitsettlement',
            unique_together={('chit', 'month')},
        ),
    ]
