# Generated by Django 3.0.7 on 2021-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0013_auto_20211006_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitsettlement',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
