# Generated by Django 3.0.7 on 2021-10-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0015_auto_20211006_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitsettlement',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
