# Generated by Django 3.0.7 on 2021-10-06 07:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0016_chitsettlement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitsettlement',
            name='betting',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
