# Generated by Django 3.0.7 on 2021-10-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0017_chitsettlement_betting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
