# Generated by Django 3.0.7 on 2021-10-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0018_auto_20211011_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitcustomers',
            name='self',
            field=models.BooleanField(default=False),
        ),
    ]
