# Generated by Django 3.0.7 on 2021-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0019_chitcustomers_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitcustomers',
            name='self',
        ),
        migrations.AddField(
            model_name='customers',
            name='self',
            field=models.BooleanField(default=False),
        ),
    ]
