# Generated by Django 3.0.7 on 2021-09-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('purchased_kms', models.IntegerField()),
                ('insurance_date', models.DateField()),
            ],
            options={
                'db_table': 'dim_car_detail',
            },
        ),
    ]
