# Generated by Django 3.0.7 on 2021-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210906_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gps_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='total_kms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
