# Generated by Django 3.0.7 on 2021-09-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210906_1940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carodometer',
            unique_together={('date', 'car')},
        ),
    ]
