# Generated by Django 3.0.7 on 2021-09-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20210906_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='ignition_status',
            field=models.BooleanField(default=0),
        ),
    ]
