# Generated by Django 3.0.7 on 2021-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210907_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gps_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
