# Generated by Django 3.2.9 on 2021-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_gps_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carodometer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
