name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Latest code
      run: |
        cd /home/praba_test
        docker-compose down
        docker-compose up -d
        docker exec -i praba_test_web_1 python3 manage.py makemigrations
        docker exec -i praba_test_web_1 python3 manage.py migrate
