name: PMS_CI
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: .
          build: npx cypress info
  build:
    runs-on: self-hosted
    needs: test
    env:
      working-directory: /home/praba_test
    steps:
      - uses: actions/checkout@v3
      - name: GIT Pull
        working-directory: ${{env.working-directory}}
        run: git pull
      - name: Docker Setup
        working-directory: ${{env.working-directory}}
        run: |
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d --build
      - name: Running Migration
        working-directory: ${{env.working-directory}}
        run: |
          docker exec -i pms_web python3 manage.py makemigrations
          docker exec -i pms_web python3 manage.py migrate
