name: PMS_CI
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:   
  BUILD:
    runs-on: self-hosted
    env:
      working-directory: /home/praba_test
    steps:
      - uses: actions/checkout@v3
      - name: GIT Pull
        working-directory: ${{env.working-directory}}
        run: git pull
      - name: Docker Setup
        if: "contains(github.event.head_commit.message, 'restart')"
        working-directory: ${{env.working-directory}}
        run: |
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d --build
      - name: Running Migration
        working-directory: ${{env.working-directory}}
        run: |
          docker exec -i pms_web python3 manage.py makemigrations
          docker exec -i pms_web python3 manage.py migrate
  UNIT_TEST:
    runs-on: ubuntu-latest
    container: cypress/included:8.7.0
    needs: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start