name: PMS_CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Migration
        run: |
          if [ -f .env.dev ]; then
            mv .env.dev .env
          fi
          cd /home/praba_test
          git pull
          docker exec -i pms_web python3 manage.py makemigrations
          docker exec -i pms_web python3 manage.py migrate
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d
