name: PMS_CI
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM and Cypress
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress
        run: npm i cypress
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start:ci
          wait-on: 'http://139.59.78.156:8888/'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/integration/*

  build:
    runs-on: self-hosted
    needs: test
    env:
      working-directory: /home/praba_test
    steps:
      - uses: actions/checkout@v3
      - name: GIT Pull
        working-directory: ${{env.working-directory}}
        run: git pull
      - name: Docker Setup
        working-directory: ${{env.working-directory}}
        run: |
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d --build
      - name: Running Migration
        working-directory: ${{env.working-directory}}
        run: |
          docker exec -i pms_web python3 manage.py makemigrations
          docker exec -i pms_web python3 manage.py migrate
