name: PMS_CI
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: yarn build

  build:
    runs-on: self-hosted
    needs: test
    env:
      working-directory: /home/praba_test
    steps:
      - uses: actions/checkout@v3
      - name: GIT Pull
        working-directory: ${{env.working-directory}}
        run: git pull
      - name: Docker Setup
        working-directory: ${{env.working-directory}}
        run: |
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d --build
      - name: Running Migration
        working-directory: ${{env.working-directory}}
        run: |
          docker exec -i pms_web python3 manage.py makemigrations
          docker exec -i pms_web python3 manage.py migrate
