name: PMS_CI
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
    name: Test on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: npm run format
      - run: npm run build
      - run: npm test
      - run: npm run check:markdown
  build:
    runs-on: self-hosted
    needs: test
    env:
      working-directory: /home/praba_test
    steps:
      - uses: actions/checkout@v3
      - name: GIT Pull
        working-directory: ${{env.working-directory}}
        run: git pull
      - name: Docker Setup
        working-directory: ${{env.working-directory}}
        run: |
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d --build
      - name: Running Migration
        working-directory: ${{env.working-directory}}
        run: |
          docker exec -i pms_web python3 manage.py makemigrations
          docker exec -i pms_web python3 manage.py migrate
