name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://pms_web
    - name: Build the Docker image
      run: |
        cd /home/praba_test/,
        docker-compose --file docker-compose.yml --env-file ./.env.dev down,
        docker-compose --file docker-compose.yml --env-file ./.env.dev up -d.