name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - docker-compose.yml
      - .env.dev
      - /home/praba_test/

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        ls -lrth
        ${GITHUB_WORKSPACE}/scripts/ci.sh
