name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    container: pms_web

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker-compose build
