name: Docker Image CI

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://pms_web
    - name: Build the Docker image
      run: |
        ls -lrth
        python3 manage.py makemigrations
        python3 manage.py migrate
