name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: pms_web
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker-compose build
